### PR TITLE
Fix includes

### PR DESCRIPTION
**Pull request by tristan957**

### CODE REVIEW

**Comment by tristan957** [comment]
Looks like the CI could use a check on something like s390x which is where I found the issue.

**Comment by mikeb01** [comment]
This specifically occurs when the build is unable to find zlib.  Need a way to force that in a specific configuration.

**Comment by tristan957** [comment]
Ahh I forgot about that. I guess I will wait for 0.11.4 then. My apologies on this.

**Comment by mikeb01** [comment]
What OS is running on the s390x?  If it is Linux, then you should just be able to add the zlib-dev package.

**Comment by tristan957** [comment]
Debian

**Comment by mikeb01** [comment]
I've pushed an explicit option to the matrix to cover this case.

**Pull request merged**
