### PR TITLE
tools: include version header file

### PR DESCRIPTION
**Pull request by marco-ippolito**
refs: https://github.com/HdrHistogram/HdrHistogram_c/issues/112
Added version header file and created a script to update it to new version.
I'm not very familiar with C projects but I hope it's good enough

### CODE REVIEW

**Comment by tniessen** [comment]
The definition in the header file should probably somehow be synced with `PROJECT_VERSION` in CMake.

**Comment by marco-ippolito** [comment]
I think it should be done by a github action for release

**Comment by marco-ippolito** [comment]
I gave it a try but I'm not confident enough with the c ecosystem to create a release pipeline, since at the moment its all manual can we go for it with a future pr?

**Comment by RafaelGSS** [comment]
cc: @nodejs/security-wg

**Comment by mikeb01** [comment]
In the end I flipped this around so the header is the source of truth for the version and had the cmake build regex parse out the version from there.

**Comment by mikeb01** [comment]
I noticed that you did not include license information in the header file.  Please can you confirm that you are happy to have this licensed under CC0 and the BSD license.  This is the [license](https://github.com/HdrHistogram/HdrHistogram_c/blob/main/LICENSE.txt) we use for hdr histogram.  License details.

**Comment by marco-ippolito** [comment]
Oh yeah absolutely, I totally forgot

**Pull request merged**
