### PR TITLE
Add pkg-config file

### PR DESCRIPTION
**Pull request by tristan957**
This is useful for doing more robust finding of `libhdr_histogram`.

### CODE REVIEW

**Comment by tristan957** [comment]
I bumped the minimum cmake to v3.12. Let me know if this is unacceptable

**Comment by mikeb01** [comment]
I'll wait until this is working until I do an 0.11.4.

**Comment by tristan957** [comment]
Sweet. I think I just fixed the issue. I will check the CI.

**Comment by tristan957** [comment]
I am not really familiar with Windows or MSVC, so I am not sure if pkg-config is popular there or if MSVC understand GNU `ld` linker flags.

**Comment by tristan957** [comment]
I picked the minimum zlib version based on the Ubuntu 20.04 version of zlib. Happy to change it if you have a target in mind.

**Comment by tristan957** [comment]
Also please double check my pkg-config file. Seems like `-lm -pthread -lrt` are required and private. `zlib` is optional and private.

**Comment by mikeb01** [comment]
It looks sane, I'm not much of a pkg-config expert either.

**Pull request merged**
