### PR TITLE
Adding Win32 Support

### PR DESCRIPTION
**Pull request by cluon**
Compiles and passes tests on GCC 4.7, 4.9, Clang 3.8, and Visual Studio 2013.

### CODE REVIEW

**Comment by mikeb01** [comment]
Excellent thank you for the pull request.  Merged.

**Comment by mikeb01** [comment]
I'm trying to get this to compile in the AppVeyor CI system.  I'm trying to build against VS 2013 (12) and I'm running into compiler errors.  It's complaining about 'unistd.h'.  If you could have a look it would be helpful.  The build log is attached.

[error.txt](https://github.com/HdrHistogram/HdrHistogram_c/files/55099/error.txt)

**Comment by cluon** [comment]
Absolutely.  You'll probably want to adjust CI to compile as Win64,
otherwise you won't have access to the 64-bit intrinsics necessary.  You
can do that with cmake -G "Visual Studio 12 Win64".  As for ZLib, can you
test with ZLib 1.2.8?

Thanks!
Phil

On Dec 7, 2015, at 11:22 PM, Michael Barker <notifications@github.com>
wrote:

I'm trying to get this to compile in the AppVeyor CI system. I'm trying to
build against VS 2013 (12) and I'm running into compiler errors. It's
complaining about 'unistd.h'. If you could have a look it would be helpful.
The build log is attached.

error.txt
<https://github.com/HdrHistogram/HdrHistogram_c/files/55099/error.txt>

—
Reply to this email directly or view it on GitHub
<https://github.com/HdrHistogram/HdrHistogram_c/pull/25#issuecomment-162799119>
.

**Comment by mikeb01** [comment]
I have it building and it runs the histogram suite of tests, but fails on the histogram log suite.  Did you get the tests to run successfully.  They can be run by running `ctest` in the cmake build directory.

**Comment by cluon** [comment]
I ran tests on all the platforms mentioned,  yes.  Windows results are
below.  Is the ZLib DLL built by your CI system available as a library?
One way to do that is to copy the built zlib.dll to the same path as the
binary for the tests.

Test project E:/ws/p1/HdrHistogram_c/_build
    Start 1: Histogram
1/2 Test #1: Histogram ........................   Passed    0.03 sec
    Start 2: HistogramLogging
2/2 Test #2: HistogramLogging .................   Passed    0.04 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) =   0.09 sec

**Pull request merged**
