### PR TITLE
Enable both x86 and x64 builds in appveyor

### PR DESCRIPTION
**Pull request by ahwayakchih**
Let's see if that works :).

### CODE REVIEW

**Comment by ahwayakchih** [comment]
OK, appveyor build process for both x64 and Win32 seems to work.

Win32 fails at the moment because of missing 2 functions:
- `_InterlockedExchange64`
- `_InterlockedExchangeAdd64`

I'm not sure why it does not fail for `native-hdr-histogram` project, but i'm guessing there's no compiler switch there (actual compile is handled by node-gyp, i'm not sure how it works internally). There's `x86` platform used there, instead of `Win32`, so maybe that's the difference (it worked in this PR too, before i added switch to different version of Visual Studio)? Sorry, i don't know much about windows environment :).

**Comment by ahwayakchih** [comment]
I added Visual Studio 2017 to appveyor matrix in hope that it maybe contains some kind of "emulation" of missing functions for Win32, but it does not (https://ci.appveyor.com/project/mikeb01/hdrhistogram-c/builds/24648909). So i reverted that to keep config simpler.

**Comment by mikeb01** [comment]
Thanks I'll have a look at it this week.

**Comment by ahwayakchih** [comment]
Thank you.

**Comment by mikeb01** [comment]
I think win32 does not like `_InterlockedExchange64`.  I think I'll need to fudge it with `_InterlockedCompareExchange64`.

**Comment by ahwayakchih** [comment]
I saw some code examples that do that within the loop, but i know nothing about Win API so i did not even try to copy that :).

**Comment by mikeb01** [comment]
I think it is working now

**Comment by ahwayakchih** [comment]
Thanks!

**Pull request merged**
