### PR TITLE
Improve CMake configuration, bump required CMake version

### PR DESCRIPTION
**Pull request by mikedld**
Modernize CMake files a bit. In particular, bump minimum required version to 3.5 (I'd like it to be as high as 3.12 but I see that some distros aren't that up to date) and add targets export so that it's possible to find and use them via `find_package()`. Remove some duplication while we're at it, and fix build ordering issue with benchmark build target. Replace some `if()`-s with generator expressions to be more concise. Link most of the dependencies to the library itself, not unit tests or examples, since that's where they're actually being used.

I didn't actually test this with CMake 3.5 (my system has 3.17.2 installed), but consulted the documentation to determine if one or another construct is available.

### CODE REVIEW

**Comment by mikedld** [comment]
I don't have access to SemaphoreCI configuration and it's using CMake 2.8.12, hence the failure. Should hopefully build on Linux otherwise (at least it does for me locally).

**Comment by mikeb01** [comment]
Seems like SemaphoreCI doesn't like that version.

**Comment by mikeb01** [comment]
I would happily accept a PR that moved it to a different CI, e.g. Github Actions as a way to get this through.

**Comment by mikedld** [comment]
Let me see what I can do. Was actually something I was thinking about for the next PR anyway.

**Comment by mikeb01** [comment]
Hi, I've merged the Github Actions PR, if you could fix up the merge conflicts I can get this one merged too.

**Pull request merged**
