### PR TITLE
Mirror include directory in source tree

### LINKED ISSUE #97: If both the static library and the shared library install options are OFF, then configure fails
`CMake Error: INSTALL(EXPORT) given unknown export "hdr_histogram-targets"`

Solution seems easy if you just check to make one is installed before the install() in the root CMakelists.txt

### PR DESCRIPTION
**Pull request by tristan957**
The include files now sit in include/hdr like they are when they are
installed.

Fixes #97

### CODE REVIEW

**Comment by tristan957** [comment]
Could not recreate https://github.com/HdrHistogram/HdrHistogram_c/issues/97.

I think it is a Meson-specific issue.

**Comment by tristan957** [comment]
@mikeb01 when do you think you will have a new release out?

**Comment by mikeb01** [comment]
I'm working on it at the moment, just waiting on CI to complete.

**Comment by tristan957** [comment]
Sweet. I will start prepping things for my project then. Thanks again for approving this and merging it.

**Comment by mikeb01** [comment]
https://github.com/HdrHistogram/HdrHistogram_c/releases/tag/0.11.3

**Comment by tristan957** [comment]
Grr. Missed an instance: https://github.com/hse-project/hse/runs/5367258541?check_suite_focus=true#step:8:17

**Pull request merged**
